/**
 * Generate drizzle/seed.sql from the static catalog.
 *
 * Usage:
 *   npx tsx scripts/generate-seed-sql.ts
 *
 * The output file is also a fallback to seed remote D1 from the CLI:
 *   wrangler d1 execute vc-stack --remote --file=./drizzle/seed.sql
 *
 * For routine seeding, prefer the admin UI at /admin/seed — it's idempotent,
 * audit-logged, and works without wrangler auth.
 */

import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { buildSeedSql } from '../src/lib/seed-sql'
import {
  STATIC_CATEGORIES,
  STATIC_TOOLS,
  FEATURED_TOOL_SLUGS,
} from '../src/lib/static-catalog'

function main() {
  const sql = [
    '-- Generated by scripts/generate-seed-sql.ts — do not edit by hand.',
    '-- Mirrors src/lib/static-catalog.ts. Re-runnable; safe on populated DBs.',
    '',
    buildSeedSql(),
    '',
  ].join('\n')

  const outPath = resolve(__dirname, '../drizzle/seed.sql')
  writeFileSync(outPath, sql)
  console.log(
    `✓ wrote ${outPath} — ${STATIC_CATEGORIES.length} categories, ${STATIC_TOOLS.length} tools, ${FEATURED_TOOL_SLUGS.length} featured`,
  )
}

main()
